#!/bin/bash

if [ -f ".app_version" ]; then
    # shellcheck disable=SC2006
    VER=`cat .app_version`
else
    VER="1.0.0"
    echo $VER > .app_version
fi

if [ -f ".build_seq" ]; then
    # shellcheck disable=SC2006
    BLD=`cat .build_seq`
else
    BLD='0'
fi

((BLD++))
echo $BLD > .build_seq
echo "Version: $VER ($BLD)" > .current_version

echo "
// Auto-generated by updateversion.sh. Do not edit.

class WebVersionInfo {
  static const String name = '$VER';
  static const int build = $BLD;
}

" > lib/version_info.dart

exit 0